project:
  type: website
  output-dir: docs
website:
  title: "Давыдова Дарья"
  navbar:
    left:
      - href: index.qmd
        text: Main Page
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

